# Generated by Django 4.2.7 on 2023-11-27 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_delete_divisionpreisdent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='accounts/images/profiles'),
        ),
    ]
