# Generated by Django 4.2.7 on 2023-11-20 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_member_first_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='last_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
