# Generated by Django 4.2.7 on 2023-11-24 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='wait_for',
        ),
        migrations.AlterField(
            model_name='event',
            name='description_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/events'),
        ),
    ]
