# Generated by Django 4.2.7 on 2023-11-24 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_remove_event_wait_for_alter_event_description_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='notify',
            field=models.BooleanField(default=False),
        ),
    ]
